apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tetris-web.fullname" . }}
  labels:
    {{- include "tetris-web.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "tetris-web.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tetris-web.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "tetris-web.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort | default 8080 }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{  .Values.app.healthPath }}
              port: {{  .Values.service.targetPort | default 8080 }}
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: {{ .Values.app.healthPath }}
              port: {{ .Values.service.targetPort | default 8080 }}
            initialDelaySeconds: 3
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
